[gamevals.varp]
agility_course_state = 64300
agility_mark_cooldown = 64301
agility_laps_gnome = 64302
agility_laps_draynor = 64303
agility_laps_alkharid = 64304
agility_laps_varrock = 64305
agility_laps_wilderness = 64306
agility_laps_barbarian = 64307
agility_wilderness_tag = 64308
agility_laps_canifis = 64309
agility_laps_falador = 64310
agility_laps_seers = 64311
agility_laps_pollnivneach = 64312
agility_laps_ardougne = 64313

[gamevals.varbit]
agility_course_progress = 64300
agility_course_id = 64301
